#!/bin/sh
### BEGIN INIT INFO
# Provides:          PiDiskLeds
# Required-Start:    $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:      2 3 4 5
# Default-Stop:
# Short-Description: Start the PiDiskLeds daemon
# Description:       A daemon that blinks an LED connected to a GPIO pin on disk activity
### END INIT INFO

PATH=/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin
NAME=PiDiskLeds
DESC="Disk activity light"
# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions
. /lib/init/vars.sh

do_start () {
        # Start disk activity light
        log_daemon_msg "Starting $DESC" "$NAME"
        PiDiskLeds -d
        log_end_msg $?
}


case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        killall PiDiskLeds
        log_end_msg $?
        ;;
  *)
        echo "Usage: PiDiskLeds [start|stop]" >&2
        exit 3
        ;;
esac

:
