#!/bin/sh
### BEGIN INIT INFO
# Provides:          PiNetLeds
# Required-Start:    $network
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the PiNetLeds daemon
# Description:       A daemon that blinks an LED connected to a GPIO pin on network activity
### END INIT INFO

PATH=/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin
NAME=PiNetLeds
DESC="Network activity light"
# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions
. /lib/init/vars.sh

do_start () {
        # Start network activity light
        log_daemon_msg "Starting $DESC" "$NAME"
        PiNetLeds -d
        log_end_msg $?
}


case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        killall PiNetLeds
        log_end_msg $?
        ;;
  *)
        echo "Usage: PiNetLeds [start|stop]" >&2
        exit 3
        ;;
esac

:
